name: Build overview-widgets IPK only
on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: 2410
  FEEDS_CONF: feeds.conf.default
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: 检查项目分支
      uses: actions/checkout@v4

    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential ccache flex gawk gettext git libncurses5-dev libssl-dev python3 python3-setuptools rsync unzip zlib1g-dev
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 下载源码
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 准备工具链
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make toolchain/install -j$(nproc) V=s

    - name: 添加overview-widgets软件源
      run: |
        cd openwrt
        git clone https://github.com/hzy306016819/luci-app-overview-widgets.git package/overview-widgets

    - name: 安装必要依赖
      run: |
        cd openwrt
        make package/utils/lua/compile V=s
        make package/feeds/luci/luci-base/compile V=s

    - name: 配置只编译overview-widgets
      run: |
        cd openwrt
        echo "CONFIG_TARGET_ROOTFS_EXT4FS=n" >> .config
        echo "CONFIG_TARGET_ROOTFS_SQUASHFS=n" >> .config
        echo "CONFIG_TARGET_IMAGES=n" >> .config
        echo "CONFIG_PACKAGE_luci-app-overview-widgets=y" >> .config
        make defconfig

    - name: 编译overview-widgets
      run: |
        cd openwrt
        make package/overview-widgets/compile -j$(nproc) V=s

    - name: 查找生成的IPK文件
      id: find_ipk
      run: |
        cd openwrt
        IPK_PATH=$(find bin -name "luci-app-overview-widgets*.ipk")
        echo "IPK_PATH=${IPK_PATH}" >> $GITHUB_OUTPUT
        echo "IPK_FILE=$(basename ${IPK_PATH})" >> $GITHUB_OUTPUT

    - name: 上传IPK文件
      uses: actions/upload-artifact@v4
      with:
        name: overview-widgets-ipk
        path: openwrt/${{ steps.find_ipk.outputs.IPK_PATH }}

    - name: 创建release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: overview-widgets-ipk-$(date +%Y%m%d%H%M)
        name: "luci-app-overview-widgets IPK $(date +%Y-%m-%d)"
        body: "Automatically built luci-app-overview-widgets IPK package"
        files: openwrt/${{ steps.find_ipk.outputs.IPK_PATH }}
        draft: false
        prerelease: false
